export const theme = {
  colors: {
    primary: '#17bebb',
    primaryDark: '#14a8a4',
    primaryLight: '#7DD3D0',
    secondary: '#E0F7F7',
    background: '#f8fafa',
    card: '#ffffff',
    text: '#2c3e50',
    textLight: '#6b7280',
    border: '#e5e7eb',
    error: '#ef4444',
    errorLight: '#fee2e2',
    success: '#10b981',
    successLight: '#d1fae5',
    white: '#ffffff',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 40,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    full: 9999,
  },
  fontSize: {
    xs: 12,
    sm: 14,
    base: 16,
    lg: 18,
    xl: 20,
    xxl: 24,
    xxxl: 32,
    huge: 48,
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
    },
  },
};
