workflows:
  fakrny_expo_android:
    name: Fakrny • Expo Android AAB
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN   # Set this in Codemagic → Environment variables (Secure)
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build Android App Bundle with EAS
        script: npx eas build -p android --profile production --non-interactive
    artifacts:
      - "**/*.aab"
    caching:
      cache_paths:
        - $HOME/.npm
        - node_modules
