workflows:
  fakrny_gradle_android:
    name: Fakrny • Android AAB (no EAS)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      groups:
        - android_signing        # provides KEYSTORE_PASSWORD, KEY_PASSWORD, KEY_ALIAS
      vars:
        ANDROID_PACKAGE: com.fakrny.app   # keep in sync with app.json

    scripts:
      - name: Install JS dependencies
        script: npm ci

      - name: Create native Android project (Expo prebuild)
        script: npx expo prebuild --platform android --non-interactive --no-install

      - name: Reinstall after prebuild
        script: npm ci

      - name: Generate keystore (first build)
        script: |
          keytool -genkeypair -v \
            -storetype JKS \
            -keystore $CM_BUILD_DIR/keystore.jks \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEY_PASSWORD" \
            -alias "$KEY_ALIAS" \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Fakrny, OU=Demandcom, O=Demandcom, L=, S=, C=US"

      - name: Configure Gradle signing
        script: |
          cat >> $CM_BUILD_DIR/android/gradle.properties <<EOF
          MYAPP_UPLOAD_STORE_FILE=keystore.jks
          MYAPP_UPLOAD_KEY_ALIAS=${KEY_ALIAS}
          MYAPP_UPLOAD_STORE_PASSWORD=${KEYSTORE_PASSWORD}
          MYAPP_UPLOAD_KEY_PASSWORD=${KEY_PASSWORD}
          EOF

          # Ensure release build uses signing config
          sed -i.bak 's/release {/release {\n            signingConfig signingConfigs.release/' \
            $CM_BUILD_DIR/android/app/build.gradle || true

          # Move keystore into android/ so Gradle can read it
          mv $CM_BUILD_DIR/keystore.jks $CM_BUILD_DIR/android/keystore.jks

      - name: Build AAB with Gradle
        script: |
          cd android
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/bundle/release/*.aab

    cache:
      cache_paths:
        - $HOME/.gradle
        - $HOME/.npm
        - node_modules
