workflows:
  fakrny_expo_eas:
    name: Fakrny • Expo EAS Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN  # Your Expo robot token from Demandcom org

    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build Android App Bundle using EAS
        script: npx eas build --platform android --profile production --non-interactive

    artifacts:
      - dist/**/*.apk
      - dist/**/*.aab
